In [1]:
import tensorflow as tf
print(tf.__version__)

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2
2.5.0-rc2


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10, 7, 4],
                     [7, 10, 5]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  4],
       [ 7, 10,  5]])>

In [7]:
matrix.ndim

2

In [8]:
matrix_2 = tf.constant([[10. , 7.],
                       [7., 10.],
                       [5., 6.]], dtype=tf.float16)
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 5.,  6.]], dtype=float16)>

In [9]:
matrix_2.ndim

2

In [10]:
tensor = tf.constant([[[10. , 7.],
                       [7., 10.],
                       [5., 6.]], 
                      
                      [[6. , 7.],
                       [6., 30.],
                       [2., 3.]]])
tensor

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[10.,  7.],
        [ 7., 10.],
        [ 5.,  6.]],

       [[ 6.,  7.],
        [ 6., 30.],
        [ 2.,  3.]]], dtype=float32)>

## Tensor with Variable

In [11]:
changable_tensor = tf.Variable([10., 8.])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([10.,  8.], dtype=float32)>

In [12]:
changable_tensor[0].assign(8)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([8., 8.], dtype=float32)>

## Creating random tensor

In [13]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2, ))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [14]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2, ))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [15]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Shuffling Tensors

In [16]:
not_shuffled = tf.constant([[12,4],
                           [3,2],
                           [5,7]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[12,  4],
       [ 5,  7],
       [ 3,  2]])>

In [17]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  2],
       [12,  4],
       [ 5,  7]])>

 ## Other ways to make tensors

In [18]:
# Ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
# zeros
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
A = tf.constant(numpy_A, shape=(2, 3, 4))

A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

## Getting info from tensor

* Shape
* rank
* axis or dimension
* size

In [22]:
A_shape = A.shape
A_rank = A.ndim
A_axis = A[:, 2, 3]
A_size = tf.size(A)

A_axis, A_rank, A_shape, A_size

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 24])>,
 3,
 TensorShape([2, 3, 4]),
 <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [23]:
large_matrix_B = tf.zeros(shape=(2,3,4,5))
large_matrix_B

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

## Indexing Tensors

In [24]:
large_matrix_B[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

## Expanding matrix

In [25]:
rank_3_matrix = tf.ones(shape=(2,3,4))
rank_3_matrix

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [26]:
tf.expand_dims(rank_3_matrix, axis=-1)

<tf.Tensor: shape=(2, 3, 4, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

## Manipulating tensors

**Basic Operations**
`+`,`-`,`*`,`/`

In [27]:
tensor = tf.constant([[10, -7], [3 ,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, -7],
       [ 3,  4]])>

In [28]:
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20,  3],
       [13, 14]])>

In [29]:
tensor = tensor - 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, -7],
       [ 3,  4]])>

In [30]:
tensor = tensor * 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, -70],
       [ 30,  40]])>

In [31]:
tensor = tensor / 10
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10., -7.],
       [ 3.,  4.]])>

In [32]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[100., -70.],
       [ 30.,  40.]])>

In [33]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1. , -0.7],
       [ 0.3,  0.4]])>

## Matrix Multiplication

In [36]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10. -7.]
 [ 3.  4.]], shape=(2, 2), dtype=float64)


<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 79., -98.],
       [ 42.,  -5.]])>

In [37]:
ten_1 = tf.constant([[1,2,5],
                    [7,2,1],
                    [3,3,3]])

ten_2 = tf.constant([[3,5],
                    [6,7],
                    [1,8]])

ten_1, ten_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>)

In [38]:
ten_mul = tf.matmul(ten_1, ten_2)
ten_mul

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [45]:
ten_2 @ tf.reshape(ten_2, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]])>

In [46]:
ten_2 @ tf.transpose(ten_2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]])>

In [49]:
tf.tensordot(ten_1, ten_2, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

## Changing the datatype

In [57]:
print(ten_1.dtype)

print(tf.cast(ten_1, dtype=tf.float64) / 3.2)

<dtype: 'int32'>
tf.Tensor(
[[0.3125 0.625  1.5625]
 [2.1875 0.625  0.3125]
 [0.9375 0.9375 0.9375]], shape=(3, 3), dtype=float64)


## Aggrigating Tensors

In [60]:
new_ten = tf.random.uniform(shape=(500, 500))
new_ten

<tf.Tensor: shape=(500, 500), dtype=float32, numpy=
array([[0.7790557 , 0.73819196, 0.9186162 , ..., 0.10057127, 0.70349157,
        0.9213711 ],
       [0.1868751 , 0.7985039 , 0.08883631, ..., 0.47699344, 0.8109751 ,
        0.5091548 ],
       [0.0613811 , 0.9851836 , 0.75963366, ..., 0.63726115, 0.54136693,
        0.03316998],
       ...,
       [0.13313913, 0.05457509, 0.6621311 , ..., 0.7322196 , 0.6060301 ,
        0.8383118 ],
       [0.5555872 , 0.46405184, 0.81347704, ..., 0.32122326, 0.43215215,
        0.85085857],
       [0.502072  , 0.06491387, 0.09556592, ..., 0.5268407 , 0.5580033 ,
        0.8450661 ]], dtype=float32)>

In [61]:
tf.abs(new_ten)

<tf.Tensor: shape=(500, 500), dtype=float32, numpy=
array([[0.7790557 , 0.73819196, 0.9186162 , ..., 0.10057127, 0.70349157,
        0.9213711 ],
       [0.1868751 , 0.7985039 , 0.08883631, ..., 0.47699344, 0.8109751 ,
        0.5091548 ],
       [0.0613811 , 0.9851836 , 0.75963366, ..., 0.63726115, 0.54136693,
        0.03316998],
       ...,
       [0.13313913, 0.05457509, 0.6621311 , ..., 0.7322196 , 0.6060301 ,
        0.8383118 ],
       [0.5555872 , 0.46405184, 0.81347704, ..., 0.32122326, 0.43215215,
        0.85085857],
       [0.502072  , 0.06491387, 0.09556592, ..., 0.5268407 , 0.5580033 ,
        0.8450661 ]], dtype=float32)>

In [63]:
tf.reduce_min(new_ten)

<tf.Tensor: shape=(), dtype=float32, numpy=7.1525574e-07>

In [64]:
tf.reduce_max(new_ten)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999857>

In [69]:
mean = tf.reduce_mean(new_ten)

In [76]:
diff = new_ten - mean

diff_sqr = tf.square(diff)

sum_diff_sqr = tf.reduce_sum(diff_sqr)

variance = sum_diff_sqr / tf.cast(tf.size(new_ten), dtype=tf.float32)
sd = tf.sqrt(variance)

sd

<tf.Tensor: shape=(), dtype=float32, numpy=0.28883353>

In [79]:
tf.math.reduce_std(new_ten)

<tf.Tensor: shape=(), dtype=float32, numpy=0.28883353>

## Squeezing  a tensor

In [84]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [85]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [86]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## one Hot encoding

In [88]:
## lIST OF indices
some_list = [0,1,2,3]

# One hot encoding
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [92]:
tf.one_hot(some_list, depth=4, on_value=True, off_value=False)

<tf.Tensor: shape=(4, 4), dtype=bool, numpy=
array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])>

## Some Extra operations

In [95]:
H = tf.range(1, 50)
H

<tf.Tensor: shape=(49,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])>

In [96]:
tf.square(H)

<tf.Tensor: shape=(49,), dtype=int32, numpy=
array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401])>

In [98]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(49,), dtype=float32, numpy=
array([1.       , 1.4142137, 1.7320509, 2.       , 2.2360682, 2.4494898,
       2.6457515, 2.8284273, 3.0000002, 3.1622777, 3.3166249, 3.4641018,
       3.6055512, 3.7416575, 3.8729835, 4.       , 4.1231055, 4.2426405,
       4.3588996, 4.4721365, 4.582576 , 4.6904163, 4.7958317, 4.8989797,
       5.       , 5.0990195, 5.196152 , 5.291503 , 5.385165 , 5.477226 ,
       5.5677643, 5.6568546, 5.744563 , 5.8309526, 5.91608  , 6.0000005,
       6.0827627, 6.1644144, 6.244998 , 6.3245554, 6.4031243, 6.480741 ,
       6.5574384, 6.6332498, 6.7082043, 6.78233  , 6.8556547, 6.9282036,
       7.       ], dtype=float32)>

In [100]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(49,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 , 2.9957323, 3.0445225, 3.0910425, 3.1354942, 3.1780539,
       3.218876 , 3.2580965, 3.295837 , 3.3322046, 3.3672957, 3.4011974,
       3.4339871, 3.465736 , 3.4965076, 3.5263605, 3.5553482, 3.583519 ,
       3.610918 , 3.637586 , 3.6635616, 3.6888795, 3.713572 , 3.7376697,
       3.7612002, 3.7841897, 3.8066626, 3.8286414, 3.8501477, 3.871201 ,
       3.8918204], dtype=float32)>

## Tensors and Numpy

In [101]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [103]:
np.array(J)

type(np.array(J))

numpy.ndarray

In [104]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [106]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding Access to GPU

In [109]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [110]:
!nvidia-smi

Mon May 10 17:30:03 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 466.27       Driver Version: 466.27       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:02:00.0 Off |                  N/A |
| N/A   47C    P8    N/A /  N/A |   3053MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Exercise